### ISSUE TITLE
Can not find kext file

### ISSUE THREAD

**Issue by StrangerZ** [vivami/grey_fox#3]
Hey, Vivami.
I came across an issue of absence of kext file (grey_fox.kext). In your shell script, you're making a copy command (cp -R) on grey_fox.kext file, copying it to the Library/Extensions branch. The problem is that there is no such file, so nothing is being copied.

Can you please tell me what is the reason of such problem?

Best regards,
Strangerz.

**Comment by vivami** [comment]
Hi Strangerz,

You’ll have to compile the project and put the compiled .kext in the same directory as the install.sh script. I have to admit, it’s a bit ugly. 

Bare in mind that due to the kext not being signed, you have to disable the kext signing checks in SIP/rootless.

**Comment by StrangerZ** [comment]
Hi Vivami,
Thanks for such a fast response! It's really nice from you.

Question 1 - what do I need for compiling the project exactly? Do I need the entire XCode installed in the system, or it will be enough to use the g++? If so, which commands will be required?

Question 2 - if there is no other way to compile without XCode, will the kext file work on another system (with Mac OS X 10.7) if I compile the project in my main system (Mac OS X 10.10.5)?

Question 3 - how to disable kext signing checks?

**Comment by vivami** [comment]
1. You'll need Xcode. 
2. That should be fine. I've set it up to be compatible with 10.6.
3. Google.

**Comment by StrangerZ** [comment]
Thank you a lot, a will try building the .kext-file with XCode.
Best regards!
